on:
  push:
    branches: [ main, dev ]
  repository_dispatch:
    types: [ locize/versionPublished ]

jobs:
  test2: Test
  name: Test
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - run: echo ${{ env.LOCIZE_PROJECT_ID }}
    - run: echo ${{ secrets.LOCIZE_PROJECT_ID }}
  test1:
    name: Update Translations
    runs-on: ubuntu-latest
    steps:
      - uses: locize/download@v1
        with:
          project-id: ${{ env.LOCIZE_PROJECT_ID }}
