name: Update translations

on:
  push:
    branches: [ main, dev ]
  repository_dispatch:
    types: [ locize/versionPublished ]

jobs:
  translation:
    name: Update translations
    if: github.event.client_payload.payload.version == 'latest'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: 'echo "field: ${{ github.event.client_payload.payload.version }}"'
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
      - uses: locize/download@v1
        with:
          project-id: 22b86ae3-1ffe-4452-bae2-fa0301dd6622
          path: ./locales
