on:
  push:
    branches: [ main, dev ]
  repository_dispatch:
    types: [ locize/versionPublished ]

jobs:
  test1:
    name: Update Translations
    runs-on: ubuntu-latest
    steps:
      - uses: locize/download@v1
      - run: echo ${{ env.LOCIZE_PROJECT_ID }}
      - run: echo ${{ secrets.LOCIZE_PROJECT_ID }}
        with:
          project-id: ${{ env.LOCIZE_PROJECT_ID }}
