on:
  push:
    branches: [ main, dev ]
  repository_dispatch:
    types: [ locize/versionPublished ]

jobs:
  test2:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo  ${{ secrets.LOCIZE_PROJECT_ID }}
  test1:
    name: Update Translations
    runs-on: ubuntu-latest
    steps:
      - uses: locize/download@v1
        with:
          project-id: 22b86ae3-1ffe-4452-bae2-fa0301dd6622
