on:
  push:
    branches: [ main, dev ]
  repository_dispatch:
    types: [ locize/versionPublished ]

jobs:
  test1:
    name: Update Translations
    runs-on: ubuntu-latest
    steps:
      - uses: locize/download@v1
        with:
          project-id: ${{ secrets.LOCIZE_PROJECT_ID }}
          path: ./locales
